# -*- coding: utf-8 -*-
"""week 1 assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUjVROxFuX8obP1aKGYrAeWUVa8e7-qD
"""

def lower_triangle(n):
    for i in range(1, n + 1):
        print("* " * i)

print("Lower Triangular Pattern:")
lower_triangle(5)

def upper_triangle(n):
    for i in range(n, 0, -1):
        print("* " * i)

print("\nUpper Triangular Pattern:")
upper_triangle(5)

def pyramid(n):
    for i in range(1, n + 1):
        print(" " * (n - i) + "* " * i)

# Example
print("\nPyramid Pattern:")
pyramid(5)